[build]
  command = "npm run build:netlify"
  publish = "public"

[build.environment]
  NODE_VERSION = "24"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Sigstore is prebundled to support Lambda with require(esm) disabled.
